### ISSUE TITLE
Quick Installation Test raises ValueError

### ISSUE THREAD

**Issue by suraj95** [mindaffect/pymindaffectBCI#4]
The quick installation test raises a ValueError.

`python3 -m mindaffectBCI.noisetag`

```
Traceback (most recent call last):
  File "/Users/srpatil/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/srpatil/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/srpatil/Desktop/Suraj/Open_Source/pymindaffectBCI/mindaffectBCI/noisetag.py", line 627, in <module>
    ntexpt.startExpt()
  File "/Users/srpatil/Desktop/Suraj/Open_Source/pymindaffectBCI/mindaffectBCI/noisetag.py", line 514, in startExpt
    *args,**kwargs))
  File "/Users/srpatil/Desktop/Suraj/Open_Source/pymindaffectBCI/mindaffectBCI/noisetag.py", line 338, in __init__
    if self.utopiaController is None : raise ValueError
ValueError
```

**Comment by jadref** [comment]
Hi Thanks for the issue, I think this is already solved in the current version -- we are iterating rapidly as we move towards release.  
Can you check:
1) if you installed with pip, can you update to the current version? (which is 0.9.7)  You can update the install with: 
```pip install --upgrade mindaffectBCI```
2) if you just cloned the repository, can you `git pull`?
3) Then re-run and (if still an issue) post the output?

**Comment by suraj95** [comment]
Yup ! That worked for me. By the way, is there anything I can do until you ship out the decoders ?
